### ISSUE TITLE
traefik image and docker mode

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#70]
How are you getting traefik to see the remote api on windows 10? I can't seem to find a way of overriding the host option from tcp://localhost:2375 to tcp://0.0.0.0:2375 or equivalent, as such using the container with docker mode fails for me as it cannot get the information about the running containers. 
By the way I am runing win 10 and Docker for Windows Beta Channel release.

**Comment by StefanScherer** [comment]
Difficult. As D4W starts dockerd.exe not as Windows service but as a child of com.docker.service.exe with the following command line

```
"C:\Program Files\Docker\Docker\Resources\dockerd.exe" -H npipe:////./pipe/docker_engine_windows --debug --experimental
```

My networks in a Win10 VM with D4W look like this:

```
PS C:\Users\vagrant> ipconfig

Windows IP Configuration


Ethernet adapter Ethernet0 2:

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::8055:9b9f:e171:58cf%9
   IPv4 Address. . . . . . . . . . . : 192.168.254.135
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.254.2

Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::3db3:e3a9:24be:72a8%3
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::d4d:78b2:d19c:abf0%6
   IPv4 Address. . . . . . . . . . . : 172.17.128.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```

So I would try to set the advanced settings like this

you can't use the daemon.json settings to add some other hosts 

```json
{
"hosts": [ "npipe:////./pipe/docker_engine_windows", "tcp://172.17.128.1:2375" ],
}
```

Unfortunately as the command line above already has the `-H` option you can't mix it the hosts in the daemon.json. And this error will appear:

```
Docker daemon failed with message:
unable to configure the Docker daemon with file C:\ProgramData\docker\config\daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [npipe:////./pipe/docker_engine_windows], from file: [npipe:////./pipe/docker_engine_windows tcp://172.17.128.1:2375])



   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

So go back to an empty settings file `{}` again.

You can instead add a port forwarding of port 2375 to the container network.

```
PS C:\Users\vagrant> netsh interface portproxy add v4tov4 listenport=2375 listenaddress=172.17.128.1 connectport=2375 connectaddress=127.0.0.1

PS C:\Users\vagrant> docker run stefanscherer/docker-cli-windows docker -H tcp://172.17.128.1:2375 version
Unable to find image 'stefanscherer/docker-cli-windows:latest' locally
latest: Pulling from stefanscherer/docker-cli-windows
bce2fbc256ea: Already exists
3ac17e2e6106: Already exists
3ee8f1b336df: Pull complete
8e4397667bb8: Pull complete
2546ad06f179: Pull complete
e7be19bf78c7: Pull complete
Digest: sha256:857db8165270274e0e30242a27728e8e7c356756da09e1bd40bcc8cf3e91ca84
Status: Downloaded newer image for stefanscherer/docker-cli-windows:latest
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

Happy hacking :-)

**Comment by StefanScherer** [comment]
And after switching back to Linux containers you still can run Windows containers using the named pipe. But then the port forwarding enables you to talk with the Linux Docker engine from a Windows container:

```
PS C:\Users\vagrant> docker -H npipe:////./pipe/docker_engine_windows run stefanscherer/docker-cli-windows docker -H tcp://172.17.128.1:2375 version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

🙃

**Comment by pennywisdom** [comment]
fantastic, thanks for this @StefanScherer. Really really helpful.

**Comment by PKrause79** [comment]
I don´t understand this solution *sorry* ... have the same problem that traefik container cannot connect to docker via tcp. Even with telnet I cannot connect on port 2375 of any network adapter of my windows 10 - so I think there is no listening tcp port by docker.
